Dialog with user, basic classes for rendering and parsing objects from .obj
gMihMih29/3D-Renderer pull request #2
Opened 2024-03-25 19:01 UTC by gMihMih29

2024-03-27 17:16 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

2024-03-27 17:16 UTC, DimaTrushin commented on src/main.cpp
> +
я бы убрал пустую строку.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/CMakeLists.txt
> +target_link_libraries(App Renderer)
лол

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +App::App(int width, int height, std::string name) : App(width, height) {
Вот тут удивил. А нахрена конструктор, чей аргумент игнорируется? У тебя должна была ругнуться система clang-tidy или cppcheck или даже ide умная умеет ругаться на не используемые аргументы функций.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +    height_ = height;
1) Не делай так. Инициализируй все переменные в списке инициализации.
2) Зачем эти переменные тут хранить. Есть подозрение, что window_ уже в себе эти данные содержит и их можно из него вынимать.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +    : window_(sf::RenderWindow(sf::VideoMode(kWidth, kHeight), "3D Renderer")), view_(&window_) {
Название "3D Renderer" это тоже магическая константа. Ее можно оформить в виде
```cpp
static constexpr const char[] kName = "3D Renderer";
```

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +}
Можно сделать
```cpp
class App {
public:
  App() = default;
  ...
private:
  ...
  width_ = kWidth;
  height_ = kHeight;
};
```
И тогда у тебя эти поля будут инициализироваться всегда этими значеними, если в конструкторе не указано иначе. А вообще я не вижу смысла хранить эти поля тут.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("New frame was rendered in " + std::to_string(t.GetTime()) + " millisecond.");
То есть у тебя pull архитектура. Тем не менее, мне не понятно, зачем надо отрисовывать что-то до запуска event loop-а. Почему нельзя на открытие окна в нем отрисовать? То есть сделать это реакцией на событие. Не только на изменение чего-либо по клавишам, но и на событие "окно открылось" или "окно показали пользователю". Такое сложно сделать, если аналогичного события нет, но я сомневаюсь что тут такая ситуация. Просто не логично такую низкоуровневую работу тут пихать.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("New frame was rendered in " + std::to_string(t.GetTime()) + " millisecond.");
Очень грязное низкоуровнево измерение времени. Я бы кидал якорь до и останавливал его после. И уже во время метода остановки этот логирующий якорь сам внутри все пишет в лог. Сообщение передавать в конструкторе.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        bool flag = false;
артефакт прошлого? убрать

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +            HandleEvent_(event);
а что если это сообщение о закрытии окна? Может быть возвращать флаг и если статус закрыть главное окно, то просто делать return во внутреннем цикле? Но в целом это не так важно. В целом выглядит неплохо, если убрать первые три строчки из run

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +            ShowNewFrame_();
А почему тут return нет? Ты предполагаешь, что может быть одновременное нажатие на клавиши?

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("Key " + std::to_string(event.key.code) + " was pressed!");
Я бы внутри этого if-а сделал вызов к вспомогательной функции
```cpp
if (event.type == sf::Event::KeyPressed)
  handleKeyEvent(event.key);
```
Тогда тебе не надо будет писать  event.key.code, будет внутри этой функции писать просто key.code внутри этой функции.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +
Что-то слишком много мусора в этой функции.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +void App::ShowNewFrame_() {
А чем это отличается от кода в начале Run? Почему назвается не ShowFrame?

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        sf::Event event;
На этот цикл хорошо бы поставить ограничитель, чтобы у тебя не сгорел комп от 100500 кадров в секунду.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("New frame was rendered in " + std::to_string(t.GetTime()) + " millisecond.");
что-то очень длинная строчка получается для обращения к логгеру. Я бы какой-нибудь псевдоним ввел.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/App.cpp
> +    {
Я только сейчас заметил тут этот scope. Это же просто вызов функции.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/ObjectParser.cpp
> +    return TriangularObject({0, 0, 0}, {0, 0, 0}, vertexes, connections);
А почему тут нет std::move(vertexes) и std::move(connections)?

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/ObjectParser.cpp
> +                    if ('0' <= params[i][j] && params[i][j] <= '9' || params[i][j] == '.' || params[i][j] == ',' ||
6 вложенных scope, даже в ядре Linux можно не более 3.

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/ObjectParser.cpp
> +TriangularObject ObjectParser::ParseObject(const std::string& path) const {
Этот метод точно нуждается в рефакторинге.
Еще есть общий вопрос. А почему у тебя не перегружены операторы operator<< и operator>> для записи в поток и чтения из потока? Это стандартный способ писать в файл и читать из файла? Или у тебя тут конвертация данных на лету происходит?

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/ObjectParser.h
> +    TriangularObject::CoordinatesVector ParsePosition(const std::string& input) const;
Не консистентный интерфейс. У тебя первый метод в виде строки принимает путь к файлу. А два других (как я понял) принимают строку с данными, которую надо распарсить.
Тут плохо все. С одной стороны у тебя парсер зачем-то взаимодействует с файловой системой, а не только парсингом занимается. Ну и парсится у тебя все и сразу. Почему нельзя было сделать парсинг каждой частички через operator>> и просто его последовательно вызывать?

2024-03-27 17:16 UTC, DimaTrushin commented on src/App/ObjectParser.cpp
> +        bool dot = false;
Везде, где есть флаги -- это ошибка дизайна. Это означает, что ты должен был вызвать функцию, которая через return вернет значение флага, но ты ее не написал и не вызвал.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Exceptions/react.cpp
> +        std::cout << "Soon there will be better try-catch";
хотя бы \n в конце строки добавь.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.h
> +#include "../Renderer/Renderer.h"
Не вижу зачем этот хедер тут. Его можно перенести в cpp файл.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.h
> +#include "../Renderer/TriangularObject.h"
Если аргумент функции зависит от ссылки или указателя. То для класса достаточно сделать forward declaration, а сам хедер поместить в cpp файл. Это локализует зависимости.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.h
> +    static constexpr double kRotationSpeedDeg = 10;
Проблема этих значений в том, что не понятно в каких единицах измерения это все происходит. Но это глобально очень нетривиально править. Пусть пока остается так. Просто даю знать о ситуации.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.h
> +    PixelScreen GetScene();
1) Не называй метод, который строит что-то с глаголом Get. Потому что у пользователя функции складывается ощущение, что он получает доступ к данным по ссылке, а не строит что-то новое и дорогостоящее. Потому лучше такие методы называть через make или create.
2) И еще сразу вопрос, почему метод не константный? Выглядит так, что у тебя нет никаких внутренних буфферов или еще чего-то, что требует пересчета. Этот метод не меняет состояние мира или камеры, он просто строит кадр по сцене. У меня большие вопросы возникают по поводу происходящего внутри.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.h
> +    void CamMoveForward();
Небольшая неконсистентность, глагол не первый в названии функции. Думаю это можно так и оставить. Но глаз зацепился.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Renderer.h
> +    static PixelScreen Render(World w, Camera c);
Ебаное говно. Ты принимаешь World по значению! Это же пиздец как дорого. Особенно на каждый вызов. Это так запланированно?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Kernel/Kernel.cpp
> +    return Renderer::Render(world_, cam_);
Посморел этот метод (лучше бы не смотрел). Ты можешь делать GetScene константным методом, и переименуй в MakeScene.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/PixelScreen.h
> +    const sf::Vertex& GetPixel(int x, int y) const;
Если делаешь метод доступа, через который можно и писать и читать, то лучше не добавлять get в его название. Можно просто сделать Pixel(int x, int y). Это будет лучше читаться на стороне пользователя класса.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/PixelScreen.h
> +    using Pixels = sf::VertexArray;
Судя по всему это класс адаптер для ядра, чтобы не работать напрямую с sfml классом VertexArray.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/PixelScreen.cpp
> +            GetPixel(j, i).position = sf::Vector2f(j, i);
1) Не понимаю, что тут происходит. У тебя же везде position имеет только дефолтное значение. Зачем тут что-то заполнять? Или оно случайное?
2) И еще вопрос. А что std::fill нельзя тут использовать? У sf::VertexArray нет методов begin и end для совместимости с stl алгоритмами?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.h
> +    using DirectionVector = Eigen::Vector3d;
Это бессмысленные названия типов. DirectionVector -- это больше подходит под имя переменной. Какая разница вектор указывает направление или скорость или ускорение? Это все будет один и тот же тип -- вектор размера 3. А вот уже для чего этот вектор используется будет указывать его тип. Сделай просто
```cpp
using Vector3 = Eigen::Vector3d;
using Matrix3x3 = Eigen::Matrix3d
using HomogeniousTransformation = Eigen::Matrix4d;

Vector3 position_;
Matrix3x3 direction_;
```

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.h
> +    const DirectionMatrix& GetDirectionMatrix() const;
Нужны ли эти методы снаружи?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.h
> +    Camera(int width, int height, const CoordinatesVector& pos, const DirectionMatrix& directions);
Такое ощущение, что маловато информации для камеры. А расстояние от фокусное точки position_ до экрана какое? А до задней стенки какое? А фоксная точка в точности по центру экрана расположена? И почему width и height указываются в int, когда у тебя все размеры указываются в double (координаты векторов и матриц). Странно что тут у тебя дискретные параметры для объекта в double мире. И еще более странно, что камера должна запоминать эти параметры.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.h
> +    int GetHeight() const;
Это выглядит как бессмысленные функции для камеры. Что такое ширина в пикселях у камеры? Это же неимеющая смысла величина. Камера в вещественных координатах оперирует.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.cpp
> +    return -directionMatrix_.col(2);
внезапно

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.cpp
> +    position_ += distance * directionMatrix_.col(0);
А почему тут не сделал метод для удобства?
Типо GetDirectionOfCamera можно назвать GetForwardDirection, а другие можно назвать GetRightDirection, GetUpDirection и так далее.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Camera.h
> +    int height_ = kHeight;
Я посмотрел, у тебя удивительным образом width_ и height_ нигде не используются. Ты их только хранишь, но у тебя ничего от них не зависит. Это максимально странно.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/MathFuncs.h
> +#include <numbers>
1) Эти хедеры тут не нужны. Спрячь их в cpp файл.
2) Если у тебя c++20, то тебе не нужны define и cmath, ты можешь использовать std::numbers::pi. А если у тебя нет c++20, то тебе не нужен numbers. Оставь что-то одно.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Renderer.cpp
> +    PixelScreen ps = PixelScreen(c.GetWidth(), c.GetHeight());
В c++ принят другой синтаксис
```cpp
PixelScreen ps(c.GetWidth(), c.GetHeight());
```

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Renderer.cpp
> +PixelScreen Renderer::Render(World w, Camera c) {
1) ну почему такие короткие имена переменных?
2) нахрена у тебя они передаются по копии. Принимай оба объекта по константной ссылке.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Triangle.h
> +    using NormalVector = Eigen::Vector3d;
избавься от такого многообразия псевдонимов.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Triangle.h
> +    using PositionMatrix = Eigen::Matrix<double, 4, 3>;
Matrix4x3 куда более информативное название.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Triangle.h
> +    PositionMatrix GetPositionMatrix() const;
create, а не get, ну или make.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Triangle.h
> +
Я правильно понимаю, у тебя нет модифицирующих методов?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/Triangle.cpp
> +    point1_ << p1(0), p1(1), p1(2), 1;
а почему нельзя было инициализировать в списке инициализации?
```cpp
point1_{p1(0), p1(1), p1(2), 1}
```
??

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.h
> +class TriangularObject {
Triangular или Triangulated? Просто я не могу понять, это треугольный объект или триангулируемый объект.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.h
> +    void SetColor(sf::Color color);
Специально не по ссылке принимается? Я просто спрашиваю на случай, что это намеренно принятое решение, а не случайность.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.h
> +    std::vector<NormalVector> GetNormalVectors() const;
Если операция возвращает дорогой объект для построения, то уж точно надо писать make или create.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.cpp
> +    surfaces_ = surfaces;
что мешало это перенести в список инициализации?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.cpp
> +                        prev += connections[j].size();
Капец опять 6 вложенных scope.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Renderer/TriangularObject.cpp
> +    std::vector<NormalVector> normals(count_vertexes, NormalVector(0, 0, 0));
У тебя тут происходит какая-то нетривиальная работа. Надо понять что это за работа и кто за нее должен отвечать.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +    const std::string kEMPTY = "";
1) Не используй CAPS_ONLY стиль для чего либо кроме макросов! Это будет путать пользователей кода. Все привыкли, что такие имена только у макросов.
2) можешь использовать си строки, тогда их можно сделать constexpr. Либо через const char* либо через const char[].
3) Почему не static!??

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +    static const Logger kLoggerFile;
Я бы предпочитал мухи отдельно котлеты отдельно. А именно. Пусть этот класс определяет logger. Это не его задача как к нему будут получать доступ. Он лишь дает тебе класс, которым ты будешь пользоваться для логирования.
А потом надо сделать другой класс, который уже будет создавать логгер глобальным синглтоном и им можно будет пользоваться извне.
```cpp
class Logger {
  // Logger implementation
};

class ConsoleLogger {
public:
  static void Log(const char* msg) {
    instance().log(msg);
  }
private:
  static Logger& instance() {
    Logger logger(...);
    return logger;
  }
};

ConsoleLogger::Log("ups");
```
И не надо будет писать миллион строчек промежуточного кода. У тебя уже класс ConsoleLogger предоставляет нужный интерфейс для передачи сообщений. Можно еще поиграться с тем, как это можно оформить. Можно сделать не через статические функции, а через методы объекта, тогда надо создать ConsolLogger как объект, но доступ он будет давать именно к глобальному Logger внутри метода instance. И тогда можно перегружать операторы вида operator<<.

Чтобы не повторять общую часть для разных логеров можно сделать так
```cpp
class ConsoleLoggerInstance {
protected:
  static Logger& instance() {
    static Logger logger(/*параметры для консольного логгера*/);
    return logger;
  }
};
class FileLoggerInstance {
protected:
  static Logger& instance() {
    static Logger logger(/*параметры для файлового логгера*/);
    return logger;
  }
};

template<class LoggerInstance>
class GLogger : LoggerInstance {
public:
  static void Log(const char* msg) {
    instance().log(msg);
  }
};

using ConsoleLogger = GLogger<ConsoleLoggerInstance>;
```

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +        fout.flush();
Мне казалось close автоматом вызывает flush

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +        auto fout = std::ofstream(path_);
А эта штука может кинуть исключение, если файл не открылся. Это нормально, что у тебя логер может от этого упасть и программа прекратит работать?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +    if (write_to_file_) {
Вообще выглядит так, что тебе нужно не флаг иметь "писать ли в файл", а иметь метод log_  который ты можешь подменять. То есть заводишь переменную
```cpp
class Logger {
  using LoggingAction = std::function<void(const std::string&, const std::string&>;
public:
  Logger() : log_(/*инициализируешь нужным действием*/) {}

  void Log(const std::string& msg, const std::string& type) {
    assert(log_);
    log_(msg, type);
  }
private:
  static LogToFile(const std::string& msg, const std::string& type) {
    // Имплементация только для записи в файл
  }
  static LogToConsole(const std::string& msg, const std::string& type) {
    // Имплементация только для записи в консоль
  }

  LoggingAction log_ = LogToConsole;
};
```
Такой подход лучше скейлится. Тебе не надо на каждый вызов log проверять в каком ты режиме. У тебя просто будет зваться тот метод, который ты туда положил. Только надо будет все время проверять assert-ами, что этот метод не пуст (потому что std::function может быть пустой после мува). Еще из недостатков, этот метод тяжело сделать шаблонным. Тогда придется продумать интерфейс заранее. Но более или менее все что угодно текстовое можно конвертировать к std::string.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +        if (use_time_stamp_) {
Аналогично можно сделать метод получения временного штампа, он либо возвращает пустую строку, либо текущее время с какой-то информацией.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.h
> +        auto fout = std::ofstream(path_);
При подходе с std::function можно хранить path внутри std::function. Это лучше локализует данные.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.cpp
> +    std::tm* now = std::localtime(&t);
Ну и гадость. Что мешало использовать std::chrono?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Logger.cpp
> +    std::time_t t = std::time(0);   // get time now
Офигенный комментарий. Нет..

2024-03-27 17:16 UTC, DimaTrushin commented on src/View/View.h
хорошо

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Timer.h
> +class Timer {
Если у тебя есть такой класс как таймер, то почему ты его нигде не используешь, а используешь какие-то низкоуровневые функции для вычисления времени? Почему у тебя этот класс не занимается предоставлением нужны методов?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Timer.h
> +    int64_t GetTime();
Лучше не выдавать абстрактное время в int64_t, лучше сделать методы вида
```cpp
int64_t getSeconds() const;
int64_t getMinutes() const;
int64_t getHours() const;
// и т.д.
```

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Timer.h
> +    ~Timer() = default;
Это лишнее.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Timer.h
> +    std::chrono::_V2::system_clock::time_point start_;
Перенеси это в конец класса для консистентности.

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/Timer.cpp
> +    Reset();
ну почему не в списке инициализации?

2024-03-27 17:16 UTC, DimaTrushin commented on src/Utilities/StringViewSplit.h
> +std::vector<std::string_view> StringViewSplit(std::string_view str, char separator);
Я предпочту не знать, что это такое.

2024-03-29 08:01 UTC, gMihMih29 commented on src/App/CMakeLists.txt
> +target_link_libraries(App Renderer)
Тут вопрос звучит так: "Почему высокоуровневый код зависит от низкоуровневой библиотеки, в которой дофига матеши, о которой App не должен париться?" ?

2024-03-29 08:13 UTC, gMihMih29 commented on src/App/App.cpp
> +            ShowNewFrame_();
Исправил на switch case

2024-03-29 08:15 UTC, gMihMih29 commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("Key " + std::to_string(event.key.code) + " was pressed!");
46 строка была для проверки, что логгер и считываение клавиш работает нормально.

2024-03-29 08:16 UTC, gMihMih29 commented on src/App/App.cpp
> +void App::ShowNewFrame_() {
Потому что забыл о существовании `ShowNewFrame_()`

2024-03-29 08:17 UTC, gMihMih29 commented on src/App/App.cpp
> +        sf::Event event;
У меня картинка не меняется до тех пор, пока не будет нажата клавиша движения или добавления нового объекта. Даже так будет +100500 кадров?

2024-03-29 08:29 UTC, gMihMih29 commented on src/Renderer/Renderer.h
> +    static PixelScreen Render(World w, Camera c);
Не запланировано, будет исправлено!

2024-03-29 08:39 UTC, gMihMih29 commented on src/Renderer/PixelScreen.cpp
> +            GetPixel(j, i).position = sf::Vector2f(j, i);
`sf::VertexArray` хранит в себе список точек, но проблема в том, что ему без разницы в каком они порядке. Я могу хоть сначала записать первую строчку пикселей, а потом последнюю и так далее, ему будет без разницы, он отрисует их правильно, так как у него есть позиция этих точек.

2024-03-29 08:46 UTC, gMihMih29 commented on src/Renderer/Camera.h
> +    Camera(int width, int height, const CoordinatesVector& pos, const DirectionMatrix& directions);
По поводу, width и height согласен. Параметры, как расстояние от position до экрана и угол обзора, были добавлены, просто не в этих коммитах.

2024-03-29 08:48 UTC, gMihMih29 commented on src/Renderer/Camera.cpp
> +    return -directionMatrix_.col(2);
Дима, можешь, пожалуйста, объяснить, в чём здесь проблема?

2024-03-29 08:50 UTC, gMihMih29 commented on src/Renderer/Camera.h
> +    int height_ = kHeight;
Согласен

2024-03-29 09:17 UTC, gMihMih29 commented on src/Renderer/Triangle.h
> +
Да

2024-03-29 09:19 UTC, gMihMih29 commented on src/Renderer/TriangularObject.h
> +class TriangularObject {
Триангулируемый

2024-03-29 09:20 UTC, gMihMih29 commented on src/Renderer/TriangularObject.h
> +    void SetColor(sf::Color color);
Там три инта хранится, решил не по ссылке передавать

2024-03-29 09:20 UTC, gMihMih29 commented on src/Renderer/TriangularObject.cpp
> +    surfaces_ = surfaces;
Невнимательность

2024-03-30 16:48 UTC, gMihMih29 commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("New frame was rendered in " + std::to_string(t.GetTime()) + " millisecond.");
Я добавил обработку события, когда на окно с рендером перешёл фокус

2024-03-30 16:50 UTC, gMihMih29 commented on src/App/App.cpp
> +            HandleEvent_(event);
Внутри метода `App::HandleEvent_` происходит проверка на ивент "Закрытие окна". Там я вызываю `window_.close();`, который в итоге и закрывает окно

2024-03-30 16:54 UTC, gMihMih29 commented on src/App/App.cpp
> +        Utilities::Logger::kConsole.Info("Key " + std::to_string(event.key.code) + " was pressed!");
Добавил метод `HandleKeyEvent_`

2024-03-30 17:05 UTC, gMihMih29 commented on src/Kernel/Kernel.h
> +    static constexpr double kRotationSpeedDeg = 10;
`kMovementSpeed `- согласен, я тоже не знаю в каких единицах измерения это, впрочем и везде не понятно в каких единицах измерения задаются точки объектов.
`kRotationSpeedDeg `- в градусах, потому что `Deg`. Внутри методов `Kernel`, связанных с поворотом, я вызываю методы поворота камеры на угол заданый в градусах, перевожу его в радианы и уже меняю матрицу поворота.

2024-03-30 17:27 UTC, gMihMih29 commented on src/App/ObjectParser.cpp
> +TriangularObject ObjectParser::ParseObject(const std::string& path) const {
Ты предлагаешь написать, что-то в виде:
```
ObjectParser parser("file");
TriangulatedObject obj;
parser >> obj;
```
?
Я сразу здесь открываю файл, читаю из него и обрабатываю данные.
Рефакторинг будет сделан.

2024-03-30 17:32 UTC, gMihMih29 commented on src/Kernel/Kernel.h
> +    PixelScreen GetScene();
Я решил добавить буффер для экрана, чтобы его не пересоздавать постоянно, заменил метод `PixelScreen GetScene();` на `const PixelScreen& MakeScene();`

2024-03-30 17:36 UTC, gMihMih29 commented on src/Kernel/Kernel.h
> +    void CamMoveForward();
Решил исправить

2024-03-30 17:45 UTC, gMihMih29 commented on src/Renderer/Camera.h
> +    Camera(int width, int height, const CoordinatesVector& pos, const DirectionMatrix& directions);
Добавил нужные конструкторы

2024-03-30 17:46 UTC, gMihMih29 commented on src/Renderer/Camera.cpp
> +    position_ += distance * directionMatrix_.col(0);
Когда исправлял повороты камеры, добавил методы `GetForwardDirectionOfCamera `и `GetRightDirectionOfCamera`

2024-03-30 18:35 UTC, gMihMih29 commented on src/Utilities/Timer.cpp
> +    Reset();
Зачем писать что-то дважды, если можно написать полтора раза?

2024-03-30 20:00 UTC, gMihMih29 commented on src/App/ObjectParser.h
> +    TriangularObject::CoordinatesVector ParsePosition(const std::string& input) const;
operator>> я понимаю, как использовать для ввода векторов, но я пока не понимаю, как его корректно сделать для ввода "face element" у объекта, в эту строку могут пихнуть хоть 7 точек, и нужно все их соединить.

2024-03-30 20:02 UTC, gMihMih29 commented on src/App/ObjectParser.cpp
> +        bool dot = false;
Я в этом месте проверяю, что в строке находится число. Точно нужно сделать отдельный метод для проверки строки на содержание числа, но без флагов я пока не понимаю как это сделать.
sign - встретился ли - в строке
dot - встретилась ли точка в строке

2024-03-30 20:04 UTC, gMihMih29 commented on src/Renderer/TriangularObject.cpp
> +                        prev += connections[j].size();
Будет исправлено!

2024-03-30 20:05 UTC, gMihMih29 commented on src/Renderer/TriangularObject.cpp
> +    std::vector<NormalVector> normals(count_vertexes, NormalVector(0, 0, 0));
Согласен, думаю над тем, чтобы перенести это в аналог ObjectParser.

2024-03-30 20:06 UTC, gMihMih29 commented on src/Utilities/Logger.h
> +        fout.flush();
Исправил!

2024-03-30 20:06 UTC, gMihMih29 commented on src/Utilities/Logger.h
> +        auto fout = std::ofstream(path_);
Добавил проверку на открытие потока

2024-03-30 20:08 UTC, gMihMih29 commented on src/Utilities/Logger.cpp
> +    std::tm* now = std::localtime(&t);
Мне показалось, что использовать то, что я использую, удобнее, нежели std::chrono + я там не нашёл того, что мне нужно (видимо потому что у меня не C++20)

2024-04-25 21:43 UTC, DimaTrushin approved these changes

2024-04-25 21:43 UTC, DimaTrushin commented on src/Renderer/PixelScreen.h
> +    const PixelScreen::Pixels& GetPixels() const;
лишний квалификатор класса. Убрать.

2024-04-26 06:11 UTC, merged